version: '3'

services:
  mysqlsrv:
    image: mysql:8.0
    container_name: my_sql_8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ml
    ports:
      - '3306:3306'
    volumes:
      - '~/localstack/ml/data/mysql:/var/lib/mysql'
      - '~/localstack/ml/data/mysql:/etc/mysql/conf.d/my.cnf'
      - '~/localstack/ml/data/mysql:/docker-entrypoint-initdb.d'